version: "3"

services:

  chatify:
    image: quay.io/soketi/soketi:latest-16-alpine
    ports:
      - "6001:6001"
      - "9601:9601"
    volumes:
      - ./chatify.json/:/app/config.json
    entrypoint: [ "node", "/app/bin/server.js", "start","--config", "/app/config.json" ]
    networks:
      chatify:


networks:
  chatify:
